language: bash

os:
- linux

env:
  - GOLANGVER=
  - GOLANGVER=1.11
  - GOLANGVER=1.10

services:
  - docker

script:
- |
  if [[ "$TRAVIS_OS_NAME" == 'linux' && -n "$GOLANGVER" ]]; then
    printf "FROM golang:${GOLANGVER}-alpine\nWORKDIR /code\nRUN apk add --update make\nENTRYPOINT []\nCMD [\"make\"]" > Dockerfile
    docker build --tag tester:${GOLANGVER}-alpine .
    docker run -it -v `pwd`:/code tester:${GOLANGVER}-alpine
  fi

notifications:
  email:
    on_success: never